### ISSUE TITLE
roidb

### ISSUE THREAD

**Issue by lzrobots** [roytseng-tw/Detectron.pytorch#128]
Hi,
I printed the `roidb` in `inputdata` from here
https://github.com/roytseng-tw/Detectron.pytorch/blob/master/tools/train_net_step.py#L422

(Pdb) input_data['roidb']
[[array([128.,   3.,  93., ..., 117.,  97.,  46.], dtype=float32)], [array([128.,   3.,  93., ..., 117.,  97.,  46.], dtype=float32)], [array([128.,   3.,  93., ..., 117.,  97.,  46.], dtype=float32)], [array([128.,   3.,  93., ..., 117.,  97.,  46.], dtype=float32)]]

(Pdb) input_data['roidb'][0][0].size
1345
(Pdb) input_data['roidb'][1][0].size
5132
(Pdb) input_data['roidb'][2][0].size
2134
(Pdb) input_data['roidb'][3][0].size
3584

I used 4 GPUs. So two questions:
1. What does printed `roidb` mean here? Why it is a array?
2. Why the size of  `roidb` on each GPU is different but their head and tail of the arrays are same? eg, 1345 on first gpu and 5132 on second gpu but the head and tail are looks same [128.,   3.,  93., ..., 117.,  97.,  46.]

Thanks.

**Comment by lzrobots** [comment]
@w-hc Thanks. So can we say it's a kind of data structure encoding? What information/metadata does it store? Is it (x, y, w, h) or something else?

And also what does the following variable mean respectively? 

`rpn_labels_int32_wide_fpn`
`rpn_bbox_targets_wide_fpn`
`rpn_bbox_inside_weights_wide_fpn`
`rpn_bbox_outside_weights_wide_fpn`

Thanks.

**Comment by w-hc** [comment]
It's a dict of many fields. You can print it out and see. 
https://github.com/roytseng-tw/Detectron.pytorch/blob/3f533b5f72abc2ec864ba5254647fec8f8f41339/lib/modeling/model_builder.py#L149

Those 4 are the labels and bbox regression targets for RPN, as their names imply. 
"wide" means that the labels and regression targets are generated on the maximum anchor field of 84 * 84 (it's 80 something. I forgot the exact number). Now an actual image may not be this big, so when computing the loss these labels are cropped here. 
https://github.com/roytseng-tw/Detectron.pytorch/blob/dddeb6f4ff9fe14e122c26ec0ab5c1928027d8dc/lib/modeling/rpn_heads.py#L135-L141
It's done this way because pytorch loaders want tensors of uniform sizes. 
As for the weights, it's easier to read it yourself than trying to explain it. 
https://github.com/roytseng-tw/Detectron.pytorch/blob/3f533b5f72abc2ec864ba5254647fec8f8f41339/lib/roi_data/rpn.py#L197-L214

**Comment by lzrobots** [comment]
@w-hc Thanks! All clear now!
