### ISSUE TITLE
Image size for training Mask Rcnn

### ISSUE THREAD

**Issue by vsd550** [roytseng-tw/Detectron.pytorch#86]
My image dataset has **images of different sizes ranging from 600 x 600 to 3000 x 3000**. Does the Mask Rcnn take a fixed size input image i.e. do I need any **preprocessing** before passing the images for training. I have made the coco-like json file for training with my dataset.
Thanks in advance

**Comment by roytseng-tw** [comment]
The preprocessing about image size is controlled by the flags: `TRAIN.SCALES`, `TRAIN.MAX_SIZE`.
An image is resized to make the smaller side as in one of the scale randomly chosen from `TRAIN.SCALES`, if the resized longer side doesn't exceed `TRAIN.MAX_SIZE`. Otherwise, image is resized to make the longer side equals to `TRAIN.MAX_SIZE`.

**Comment by vsd550** [comment]
Thanks a lot
